[package]
name = "rs-tetris-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
[dependencies]
fumen = "0.1.2"
js-sys = "0.3.68"
tsify = "0.4.5"
wasm-bindgen = "0.2"
